### ISSUE TITLE
Nodejs Npm install help!

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [city41/sromcrom#8]
Hello, so anyways I want to install the sromcrom program using npm but when I try to type the install command in the terminal it gives me a npm install error! So here is the question how do I fix the error message?

**Comment by city41** [comment]
What is the error message? You should always provide as many details as you can when asking for help. 
  
If you are not familiar with node and npm, I recommend learning about them. Maybe [this tutorial](https://www.youtube.com/watch?v=TlB_eWDSMt4)? I dunno, I just googled for it.

I'm sorry but I can't provide basic node help, I just don't have the time for it.

**Comment by NeoGeoFreak2004** [comment]
Update: sorry for bugging you but this is the output of the installation error.
"Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/@city41/sromcrom/node_modules/canvas/.node-gyp'
idk what this means so can you help me with this error please.
